version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: node
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
    - mongo-compose-network
  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: renatogroffe
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
    links:
    - mongo
    networks:
    - mongo-compose-network
volumes:
  mongodb_data:
networks:
  mongo-compose-network:
    driver: bridge